# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('tagnum', models.CharField(max_length=200)),
                ('limlow', models.CharField(max_length=200)),
                ('limhigh', models.CharField(max_length=200)),
                ('limlowlow', models.CharField(max_length=200)),
                ('limhighhigh', models.CharField(max_length=200)),
                ('required', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantdata.Group')),
            ],
        ),
    ]
